{% set version = "1.1.1" %}

package:
  name: "srt-py"
  version: "{{ version }}"

source:
  path: ../

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy
    - dash
    - dash-bootstrap-components
    - dash-html-components
    - dash-core-components
    - digital_rf
    - gnuradio-core
    - gnuradio-zeromq
    - gnuradio-osmosdr
    - pandas
    - plotly
    - pyserial
    - python >=3.6
    - pyzmq
    - numpy
    - rtl-sdr
    - scipy
    - soapysdr
    - soapysdr-module-rtlsdr
    - waitress
    - yamale

test:
  requires:
    - pytest
  imports:
    - srt

about:
  home: https://github.com/MITHaystack/srt-py
  summary: Small Radio Telescope Control Code for Python
  license: MIT
  license_file: license
